import * as React from 'react';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
//Context
import {AppGlobalsProvider} from '@/contexts/AppGlobalsContext';
import local from 'next/font/local';

//Metadata
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//Fonts
const f_inno = local({
  src: [
    {
      path: '../public/fonts/inno.otf',
    },
  ],
  variable: '--font-deacon',
});        

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <AppGlobalsProvider>
          {props.children}
          </AppGlobalsProvider>
          </ThemeRegistry>
      </body>
    </html>
  );
}
