import * as React from 'react';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
//Context
import {AppGlobalsProvider} from '@/contexts/AppGlobalsContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <AppGlobalsProvider>
          {props.children}
          </AppGlobalsProvider>
          </ThemeRegistry>
      </body>
    </html>
  );
}
